.dashVizzu_js_metadata <- function() {
deps_metadata <- list(`dash_vizzu` = structure(list(name = "dash_vizzu",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashVizzu.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVizzu",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vizzu` = structure(list(name = "dash_vizzu",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashVizzu.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVizzu",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vizzu` = structure(list(name = "dash_vizzu",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vizzu.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVizzu",
all_files = FALSE), class = "html_dependency"),
`dash_vizzu` = structure(list(name = "dash_vizzu",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vizzu.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVizzu",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
